from .models import Event
from django.utils import timezone
import json

event_list = [
    {
        'external_id': 'TM001A2B3C4D5E6F',
        'source_api': 'Ticketmaster',
        'name': 'Rock Legends Reunion Tour',
        'description': 'A spectacular night featuring legendary rock bands from the 80s and 90s.',
        'start_datetime': timezone.datetime(2025, 9, 15, 19, 30, 0,),
        'end_datetime': timezone.datetime(2025, 9, 15, 23, 0, 0,),
        'timezone': 'America/New_York',
        'event_url': 'https://www.ticketmaster.com/rock-legends-reunion',
        'image_url': 'https://example.com/images/rock_legends.jpg',
        'status': 'active',
        'category': 'Music',
        'genre': 'Rock',
        'venue_name': 'Madison Square Garden',
        'venue_address_line1': '4 Pennsylvania Plaza',
        'venue_address_line2': '',
        'venue_city': 'New York',
        'venue_state': 'NY',
        'venue_postal_code': '10001',
        'venue_country': 'United States',
        'venue_latitude': 40.7505,
        'venue_longitude': -73.9934,
        'primary_performer_name': 'The Rockers',
        'raw_api_data': json.dumps({"tm_id": "TM001A2B3C4D5E6F", "name": "Rock Legends", "venue": {"name": "MSG"}}),
        'last_synced_at': timezone.now(),
    },
    {
        'external_id': 'EB002G7H8I9J0K1L',
        'source_api': 'Eventbrite',
        'name': 'Annual Tech Conference 2025',
        'description': 'Explore the latest in AI, Machine Learning, and Web Development. Keynote speakers and workshops.',
        'start_datetime': timezone.datetime(2025, 10, 5, 9, 0, 0,),
        'end_datetime': timezone.datetime(2025, 10, 7, 17, 0, 0,),
        'timezone': 'America/Los_Angeles',
        'event_url': 'https://www.eventbrite.com/e/tech-conference-2025',
        'image_url': 'https://example.com/images/tech_conf.png',
        'status': 'active',
        'category': 'Conference',
        'genre': 'Technology',
        'venue_name': 'Los Angeles Convention Center',
        'venue_address_line1': '1201 S Figueroa St',
        'venue_address_line2': '',
        'venue_city': 'Los Angeles',
        'venue_state': 'CA',
        'venue_postal_code': '90015',
        'venue_country': 'United States',
        'venue_latitude': 34.0407,
        'venue_longitude': -118.2695,
        'primary_performer_name': 'Tech Innovators Inc.',
        'raw_api_data': json.dumps({"eb_id": "EB002G7H8I9J0K1L", "name": "Tech Conf"}),
        'last_synced_at': timezone.now(),
    },
    {
        'external_id': 'TM003M4N5O6P7Q8R',
        'source_api': 'Ticketmaster',
        'name': 'National Basketball Championship',
        'description': 'Finals game of the national basketball league. High stakes and thrilling action.',
        'start_datetime': timezone.datetime(2025, 6, 20, 20, 0, 0,),
        'end_datetime': timezone.datetime(2025, 6, 20, 22, 30, 0,),
        'timezone': 'America/Toronto',
        'event_url': 'https://www.ticketmaster.ca/basketball-championship',
        'image_url': 'https://example.com/images/basketball_final.jpg',
        'status': 'active',
        'category': 'Sports',
        'genre': 'Basketball',
        'venue_name': 'Scotiabank Arena',
        'venue_address_line1': '40 Bay St',
        'venue_address_line2': '',
        'venue_city': 'Toronto',
        'venue_state': 'ON',
        'venue_postal_code': 'M5J 2L2',
        'venue_country': 'Canada',
        'venue_latitude': 43.6433,
        'venue_longitude': -79.3791,
        'primary_performer_name': 'National Basketball League',
        'raw_api_data': json.dumps({"tm_id": "TM003M4N5O6P7Q8R", "name": "Basketball Final"}),
        'last_synced_at': timezone.now(),
    },
    {
        'external_id': 'EB004S9T0U1V2W3X',
        'source_api': 'Eventbrite',
        'name': 'Local Food & Wine Festival',
        'description': 'Taste the best local cuisine and wines. Family-friendly event with live music.',
        'start_datetime': timezone.datetime(2025, 7, 25, 11, 0, 0,),
        'end_datetime': timezone.datetime(2025, 7, 27, 20, 0, 0,),
        'timezone': 'Europe/London',
        'event_url': 'https://www.eventbrite.co.uk/e/food-wine-festival',
        'image_url': 'https://example.com/images/food_wine_fest.jpg',
        'status': 'active',
        'category': 'Festival',
        'genre': 'Food & Drink',
        'venue_name': 'Hyde Park',
        'venue_address_line1': 'Hyde Park',
        'venue_address_line2': '',
        'venue_city': 'London',
        'venue_state': '',
        'venue_postal_code': 'W2 2UH',
        'venue_country': 'United Kingdom',
        'venue_latitude': 51.5074,
        'venue_longitude': -0.1657,
        'primary_performer_name': 'London Food Events',
        'raw_api_data': json.dumps({"eb_id": "EB004S9T0U1V2W3X", "name": "Food Fest"}),
        'last_synced_at': timezone.now(),
    },
    {
        'external_id': 'TM005Y4Z5A6B7C8D',
        'source_api': 'Ticketmaster',
        'name': 'Classical Symphony Orchestra',
        'description': 'An evening of classical masterpieces performed by the city symphony orchestra.',
        'start_datetime': timezone.datetime(2025, 11, 10, 19, 0, 0,),
        'end_datetime': timezone.datetime(2025, 11, 10, 21, 30, 0,),
        'timezone': 'America/Chicago',
        'event_url': 'https://www.ticketmaster.com/symphony-orchestra',
        'image_url': 'https://example.com/images/symphony.jpg',
        'status': 'active',
        'category': 'Arts & Theater',
        'genre': 'Classical',
        'venue_name': 'Chicago Symphony Center',
        'venue_address_line1': '220 S Michigan Ave',
        'venue_address_line2': '',
        'venue_city': 'Chicago',
        'venue_state': 'IL',
        'venue_postal_code': '60604',
        'venue_country': 'United States',
        'venue_latitude': 41.8762,
        'venue_longitude': -87.6297,
        'primary_performer_name': 'Chicago Symphony Orchestra',
        'raw_api_data': json.dumps({"tm_id": "TM005Y4Z5A6B7C8D", "name": "Symphony"}),
        'last_synced_at': timezone.now(),
    },
    {
        'external_id': 'EB006E9F0G1H2I3J',
        'source_api': 'Eventbrite',
        'name': 'Startup Pitch Competition',
        'description': 'Watch promising startups pitch their ideas to a panel of investors and experts.',
        'start_datetime': timezone.datetime(2025, 12, 1, 10, 0, 0,),
        'end_datetime': timezone.datetime(2025, 12, 1, 16, 0, 0,),
        'timezone': 'Asia/Tokyo',
        'event_url': 'https://www.eventbrite.jp/e/startup-pitch-tokyo',
        'image_url': 'https://example.com/images/startup_pitch.png',
        'status': 'active',
        'category': 'Business & Professional',
        'genre': 'Networking',
        'venue_name': 'Tokyo International Forum',
        'venue_address_line1': '3 Chome-5-1 Marunouchi',
        'venue_address_line2': '',
        'venue_city': 'Tokyo',
        'venue_state': 'Tokyo',
        'venue_postal_code': '100-0005',
        'venue_country': 'Japan',
        'venue_latitude': 35.6762,
        'venue_longitude': 139.6503,
        'primary_performer_name': 'Tokyo Startup Hub',
        'raw_api_data': json.dumps({"eb_id": "EB006E9F0G1H2I3J", "name": "Startup Pitch"}),
        'last_synced_at': timezone.now(),
    },
    {
        'external_id': 'TM007K4L5M6N7O8P',
        'source_api': 'Ticketmaster',
        'name': 'Monster Truck Jam',
        'description': 'High-flying, car-crushing monster truck action for the whole family!',
        'start_datetime': timezone.datetime(2026, 1, 20, 14, 0, 0,),
        'end_datetime': timezone.datetime(2026, 1, 20, 16, 30, 0,),
        'timezone': 'America/Denver',
        'event_url': 'https://www.ticketmaster.com/monster-truck-jam',
        'image_url': 'https://example.com/images/monster_truck.jpg',
        'status': 'active',
        'category': 'Sports',
        'genre': 'Motorsports',
        'venue_name': 'Empower Field at Mile High',
        'venue_address_line1': '1701 Bryant St',
        'venue_address_line2': '',
        'venue_city': 'Denver',
        'venue_state': 'CO',
        'venue_postal_code': '80204',
        'venue_country': 'United States',
        'venue_latitude': 39.7439,
        'venue_longitude': -105.0201,
        'primary_performer_name': 'Monster Jam',
        'raw_api_data': json.dumps({"tm_id": "TM007K4L5M6N7O8P", "name": "Monster Truck"}),
        'last_synced_at': timezone.now(),
    },
    {
        'external_id': 'EB008Q9R0S1T2U3V',
        'source_api': 'Eventbrite',
        'name': 'Yoga & Meditation Retreat',
        'description': 'A weekend retreat to relax, rejuvenate, and find inner peace.',
        'start_datetime': timezone.datetime(2025, 9, 1, 8, 0, 0,),
        'end_datetime': timezone.datetime(2025, 9, 3, 17, 0, 0,),
        'timezone': 'America/Vancouver',
        'event_url': 'https://www.eventbrite.ca/e/yoga-retreat-vancouver',
        'image_url': 'https://example.com/images/yoga_retreat.png',
        'status': 'active',
        'category': 'Health & Wellness',
        'genre': 'Yoga',
        'venue_name': 'The Serene Sanctuary',
        'venue_address_line1': '123 Forest Path',
        'venue_address_line2': '',
        'venue_city': 'Vancouver',
        'venue_state': 'BC',
        'venue_postal_code': 'V6B 1C1',
        'venue_country': 'Canada',
        'venue_latitude': 49.2827,
        'venue_longitude': -123.1207,
        'primary_performer_name': 'Mindful Living Institute',
        'raw_api_data': json.dumps({"eb_id": "EB008Q9R0S1T2U3V", "name": "Yoga Retreat"}),
        'last_synced_at': timezone.now(),
    },
    {
        'external_id': 'TM009W4X5Y6Z7A8B',
        'source_api': 'Ticketmaster',
        'name': 'Disney On Ice: Frozen & Encanto',
        'description': 'Skate into the magic with your favorite Disney characters from Frozen and Encanto.',
        'start_datetime': timezone.datetime(2025, 12, 26, 13, 0, 0,),
        'end_datetime': timezone.datetime(2025, 12, 26, 15, 0, 0,),
        'timezone': 'America/New_York',
        'event_url': 'https://www.ticketmaster.com/disney-on-ice-frozen-encanto',
        'image_url': 'https://example.com/images/disney_on_ice.jpg',
        'status': 'active',
        'category': 'Family',
        'genre': 'Childrens',
        'venue_name': 'Barclays Center',
        'venue_address_line1': '620 Atlantic Ave',
        'venue_address_line2': '',
        'venue_city': 'Brooklyn',
        'venue_state': 'NY',
        'venue_postal_code': '11217',
        'venue_country': 'United States',
        'venue_latitude': 40.6827,
        'venue_longitude': -73.9750,
        'primary_performer_name': 'Disney On Ice',
        'raw_api_data': json.dumps({"tm_id": "TM009W4X5Y6Z7A8B", "name": "Disney Ice"}),
        'last_synced_at': timezone.now(),
    },
    {
        'external_id': 'EB010C9D0E1F2G3H',
        'source_api': 'Eventbrite',
        'name': 'Advanced Python Workshop',
        'description': 'Deep dive into advanced Python concepts: decorators, metaclasses, and async programming.',
        'start_datetime': timezone.datetime(2025, 11, 20, 18, 0, 0,),
        'end_datetime': timezone.datetime(2025, 11, 20, 21, 0, 0,),
        'timezone': 'Europe/Berlin',
        'event_url': 'https://www.eventbrite.de/e/advanced-python-workshop',
        'image_url': 'https://example.com/images/python_workshop.png',
        'status': 'active',
        'category': 'Science & Tech',
        'genre': 'Programming',
        'venue_name': 'Tech Hub Berlin',
        'venue_address_line1': 'Invalidenstraße 118',
        'venue_address_line2': '',
        'venue_city': 'Berlin',
        'venue_state': 'Berlin',
        'venue_postal_code': '10115',
        'venue_country': 'Germany',
        'venue_latitude': 52.5284,
        'venue_longitude': 13.3768,
        'primary_performer_name': 'Pythonistas Berlin',
        'raw_api_data': json.dumps({"eb_id": "EB010C9D0E1F2G3H", "name": "Python Workshop"}),
        'last_synced_at': timezone.now(),
    },
]

def create_events():
    for e in event_list:
        obj = Event.objects.create(
            external_id = e['external_id'],
            source_api = e['source_api'],
            name = e['name'],
            description = e['description'],
            start_datetime = e['start_datetime'],
            end_datetime = e['end_datetime'],
            timezone = e['timezone'],
            event_url = e['event_url'],
            genre= e['genre'],
            image_url = e['image_url'],
            venue_name = e['venue_name'],
            raw_api_data = e['raw_api_data']

            
        )
        

